- hosts: all
  tasks:
    - copy:
        src: /home/ubuntu/abc.txt
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: 777  
    - file:
        path: /home/ubuntu/playbooks
        state: directory
